# Generated by Django 6.0.3 on 2026-03-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
