# Generated by Django 6.0.3 on 2026-03-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_delete_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер вопроса')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время показа вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос в игре',
                'verbose_name_plural': 'Вопросы в игре',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='Время на ответ (сек)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название команды')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль для входа')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Цвет команды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название игры')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('prep', 'Подготовка'), ('active', 'Активна'), ('finished', 'Завершена')], default='prep', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('current_game_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.gamequestion', verbose_name='Текущий вопрос')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='quiz.gamesession'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Время присоединения')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='quiz.gamesession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz.team')),
            ],
            options={
                'verbose_name': 'Участие команды',
                'verbose_name_plural': 'Участия команд',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elapsed_time', models.FloatField(blank=True, null=True, verbose_name='Время ответа (сек)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='Выбранный вариант')),
                ('game_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.gamequestion', verbose_name='Вопрос в игре')),
                ('team_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.teamsession', verbose_name='Команда в сессии')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gamequestion',
            unique_together={('game_session', 'order')},
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_choice_per_question'),
        ),
        migrations.AlterUniqueTogether(
            name='teamsession',
            unique_together={('team', 'game_session')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('team_session', 'game_question')},
        ),
    ]
