# Generated by Django 6.0.3 on 2026-05-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_image'),
        ('quiz', '0006_remove_choice_questionimage_order'),
    ]

    operations = [
    ]
