# Generated by Django 6.0.3 on 2026-05-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_merge_20260513_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='questionimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение вопроса', 'verbose_name_plural': 'Изображения вопроса'},
        ),
    ]
