# Generated by Django 6.0.3 on 2026-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_choice_options_alter_questionimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
    ]
